"""training students

Revision ID: 1ebbd5a2c043
Revises: 7983714ba560
Create Date: 2018-11-05 21:42:40.810000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1ebbd5a2c043'
down_revision = '7983714ba560'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_students',
    sa.Column('training_id', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.ForeignKeyConstraint(['training_id'], ['training.id'], )
    )
    op.alter_column(u'student', 'degree',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(u'student', 'degree',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
    op.drop_table('training_students')
    # ### end Alembic commands ###
