"""training comments

Revision ID: acddb2cacb38
Revises: 1ebbd5a2c043
Create Date: 2018-11-12 00:46:51.115567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acddb2cacb38'
down_revision = '1ebbd5a2c043'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training', sa.Column('comments', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('training', 'comments')
    # ### end Alembic commands ###
